### ISSUE TITLE
Unicode parsing

### ISSUE THREAD

**Issue by woble** [subhaze/CSS-Extended#50]
Files containing for example Chinese characters do not get parsed and the plugin produces an error similar to this:

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 885: character maps to <undefined>
```

Easy way to fix this is to modify `style_parser.py` on lines 99 and 131 by adding `encoding='utf8'` to the `open` function.

Before:

``` python
 98            get_output_panel().set_name(file_path)
 99            with open(file_path, 'r') as f:
100                content = f.read()
```

After:

``` python
 98            get_output_panel().set_name(file_path)
 99            with open(file_path, 'r', encoding='utf8') as f:
100                content = f.read()
```

**Comment by subhaze** [comment]
I've merged @katerlouis PR, so this should hopefully be fixed.
